language: ruby
rvm:
  - 2.0.0
  - 2.1.0
env:
  - DB=postgresql
bundler_args: --without development --path vendor/bundle
script:
  - "bundle exec rake spec"
notifications:
  webhooks:
    - https://idobata.io/hook/d23ae9ac-fc1e-4220-8770-9b8cfd1d0d17
